name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install docker
        run: |
          brew install docker act
          echo "-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest" > ~/.actrc
          colima start
          echo DOCKER_HOST="unix:///${HOME}/.colima/default/docker.sock" >> $GITHUB_ENV
      - run: |
          docker ps
          echo $DOCKER_HOST
          act -j tests
